pipeline {
    agent any
    
    tools {
        jdk 'JAVA11'
        maven 'Maven392'
    }
    
    stages {
            stage('Which Java?') {
                steps {
                    sh 'java --version'
                }
            }
            stage ('Build') {
                steps {     
                    env.JAVA_HOME="${tool 'JAVA11'}"               
                    sh "mvn clean verify"                    
                }
            }

    }
}