pipeline {
    agent any
    environment {
        JAVA_HOME '/var/jenkins_home/tools/hudson.model.JDK/JAVA11'
    }
    
    tools {
        jdk 'JAVA11'
        maven 'Maven392'
    }
    
    stages {
            stage('Which Java?') {
                steps {
                    sh 'java --version'
                }
            }
            stage ('Build') {
                steps {                   
                    sh "mvn clean verify"                    
                }
            }

    }
}